pipeline {
    agent any

    environment {
        GIT_REPO           = 'https://github.com/jhromeroabx/WebApi_DOTNET.git'
        GIT_BRANCH         = 'develope'
        SONAR_PROJECT_KEY  = 'miniowebapi'
        SONAR_HOST_URL     = 'https://sonarqubeloasi.share.zrok.io'
        JAVA_HOME          = '/usr/lib/jvm/java-17-openjdk-amd64'
        PATH               = "${JAVA_HOME}/bin:${PATH}"
    }

    stages {
        stage('Clone Repository') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: "*/${env.GIT_BRANCH}"]],
                    extensions: [[$class: 'WipeWorkspace']],
                    userRemoteConfigs: [[
                        url: env.GIT_REPO,
                        credentialsId: 'github-j'
                    ]]
                ])
            }
        }

        /*stage('Análisis SonarQube') {
            steps {
                withSonarQubeEnv('SonarQube Loasi') {
                    withCredentials([string(credentialsId: 'sonar-token', variable: 'SONAR_TOKEN')]) {
                        script {
                            def scannerHome = tool 'SonarScanner'
                            sh """
                                set +x
                                echo 'Java version usada:'
                                java -version

                                "${scannerHome}/bin/sonar-scanner" \\
                                  -Dsonar.projectKey="${SONAR_PROJECT_KEY}" \\
                                  -Dsonar.sources=. \\
                                  -Dsonar.login="${SONAR_TOKEN}" \\
                                  -Dsonar.host.url="${SONAR_HOST_URL}"
                            """
                        }
                    }
                }
            }
        }


        stage('Esperar análisis SonarQube') {
            steps {
                timeout(time: 10, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }*/

        stage('Levantar App con Docker Compose') {
    steps {
        script {
            dir("${env.WORKSPACE}") {
                sh '''
                    docker-compose -f docker-compose.yml down || true
                    docker-compose -f docker-compose.yml build --no-cache
                    docker-compose -f docker-compose.yml up -d
                    docker-compose -f docker-compose.yml ps
                '''
                    }
                }
            }
        }
    }
}
