pipeline {
    agent any

    environment {
        SONAR_PROJECT_KEY = 'miniowebapi'
    }

    stages {
        stage('Clone Repository') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/main']],
                    extensions: [[$class: 'WipeWorkspace']],
                    userRemoteConfigs: [[
                        url: 'https://github.com/jhromeroabx/WebApi_DOTNET.git',
                        credentialsId: 'github-j'
                    ]]
                ])
            }
        }

  stage('Análisis SonarQube') {
    steps {
        withSonarQubeEnv('SonarQube Loasi') {
            dir("${env.WORKSPACE}") {
                withCredentials([string(credentialsId: 'sonar-token', variable: 'SONAR_TOKEN')]) {
                    withEnv([
                        'JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64',
                        'PATH+JDK=/usr/lib/jvm/java-17-openjdk-amd64/bin'
                    ]) {
                        script {
                            def scannerHome = tool 'SonarScanner'
                            sh """
                                echo 'Java version usada:'
                                java -version

                                ${scannerHome}/bin/sonar-scanner \\
                                -Dsonar.projectKey=${env.SONAR_PROJECT_KEY} \\
                                -Dsonar.sources=. \\
                                -Dsonar.login=$SONAR_TOKEN \\
                                -Dsonar.host.url=https://sonarqube123.share.zrok.io
                            """
                        }
                    }
                }
            }
        }
    }
}


        stage('Esperar análisis SonarQube') {
            steps {
                timeout(time: 10, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }
    }
}
