sonar.projectKey=miniowebapi
sonar.projectName=miniowebapi
sonar.projectVersion=1.0

sonar.host.url=https://sonarqube123.share.zrok.io

sonar.sources=.
sonar.exclusions=**/bin/**,**/obj/**

sonar.cs.opencover.reportsPaths=TestResults/Coverage.opencover.xml
